# Generated by Django 5.0.4 on 2024-04-17 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qoshiq',
            name='fayl',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
